### ISSUE TITLE
Missing eds_descriptors field

### ISSUE THREAD

**Issue by drh-stanford** [ebsco/edsapi-ruby#42]
the "Descriptors" field appears to be missing from the EDS gem -- see https://web.a.ebscohost.com/ehost/detail/detail?vid=0&sid=db1dd141-0a52-48ff-b6c5-2d56b0ea4f64%40sessionmgr4009&bdata=JnNpdGU9ZWhvc3QtbGl2ZSZzY29wZT1zaXRl#AN=IND605263032&db=agr

Here's the data we're seeing in the SolrDocument:

```yml
--- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
eds_accession_number: S0378429016300958
eds_database_id: edselp
eds_database_name: ScienceDirect
eds_access_level: '6'
eds_relevancy_score: '1189'
eds_title: Yield, growth and grain nitrogen response to elevated CO2 of five field
  pea (Pisum sativum L.) cultivars in a low rainfall environment
eds_source_title: Field Crops Research
eds_composed_title: In <searchLink fieldCode="JN" term="%22Field+Crops+Research%22">Field
  Crops Research</searchLink> September 2016 196:1-9
eds_other_titles: 
eds_abstract: Atmospheric CO<subscript>2</subscript> concentrations have been increasing
  from about 280ppm to 400ppm from the pre-industrial era until now. If intraspecific
  variability in the response to elevated CO<subscript>2</subscript> (e[CO<subscript>2</subscript>])
  can be found, then it should be possible to select for greater responsiveness in
  crop breeding programs. Our experiment aimed to determine the effects of e[CO<subscript>2</subscript>]
  on the yield, biomass, leaf and grain nitrogen content of a range of field pea (Pisum
  sativum L.) cultivars subjected to rainfed and supplemental irrigation conditions.
  Plants were grown under Free Air CO<subscript>2</subscript> Enrichment (FACE) at
  the Australian Grains FACE facility in Horsham, Victoria, Australia under e[CO<subscript>2</subscript>]
  (550ppm) or at ambient CO<subscript>2</subscript> (390–400ppm) under rainfed conditions
  and supplemental irrigation during three seasons, 2010–2012. Yields were significantly
  increased by 26% under e[CO<subscript>2</subscript>] due to an increase in the number
  of pods per area. Grain size, the number of grains per pod and the harvest index
  remained unaffected by e[CO<subscript>2</subscript>]. Grain nitrogen concentration
  ([N]) was slightly, but significantly, decreased by e[CO<subscript>2</subscript>],
  but this was not consistent across cultivars under all water regimes. The dual purpose
  cultivar PBA Hayman consistently maintained grain [N] in response to e[CO<subscript>2</subscript>]
  while the response in grain [N] in the cultivars Sturt and PBA Twilight depended
  on the irrigation treatment. While there was no evidence for consistent differences
  in seed yield response to e[CO<subscript>2</subscript>] for the chosen cultivars,
  understanding the mechanisms for why some cultivars are able to maintain [N] under
  e[CO<subscript>2</subscript>] would allow breeding programs to develop varieties
  resistant to decreases in [N] under e[CO<subscript>2</subscript>].
eds_authors: Bourgault, Maryse; Brand, Jason; Tausz, Michael; Fitzgerald, Glenn J.
eds_author_affiliations: 
eds_subjects: []
eds_subjects_geographic: 
eds_subjects_person: 
eds_author_supplied_keywords: 
eds_notes: 
eds_languages:
- English
eds_page_count: '9'
eds_page_start: '1'
eds_physical_description: 
eds_publication_type: Academic Journal
eds_publication_type_id: academicJournal
eds_publication_date: '2016-09-01'
eds_publication_year: '2016'
eds_publication_info: 
eds_document_type: 
eds_document_doi: 10.1016/j.fcr.2016.04.011
eds_document_oclc: 
eds_issn_print: 
eds_issns:
- '03784290'
eds_isbn_print: 
eds_isbns_related: 
eds_isbn_electronic: 
eds_isbns: []
eds_series: 
eds_volume: '196'
eds_issue: 
eds_covers: []
eds_cover_thumb_url: 
eds_cover_medium_url: 
eds_fulltext_word_count: 0
eds_result_id: 1
eds_plink: http://search.ebscohost.com/login.aspx?direct=true&site=eds-live&db=edselp&AN=S0378429016300958
eds_html_fulltext: 
eds_images: []
eds_all_links:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  url: http://library.stanford.edu/sfx?ID=doi:10.1016%2Fj.fcr.2016.04.011&genre=article&atitle=Yield%2C%20growth%20and%20grain%20nitrogen%20response%20to%20elevated%20CO2%20of%20five%20field%20pea%20%28Pisum%20sativum%20L.%29%20cultivars%20in%20a%20low%20rainfall%20environment&title=Field
    Crops Research&issn=03784290&isbn=&volume=196&issue=&date=20160901&aulast=Bourgault,
    Maryse&spage=1&pages=1-9&sid=EBSCO:ScienceDirect:S0378429016300958
  label: Check SFX for full text
  icon: http://library.stanford.edu/sfx/img/sfxmenu/SFXFinal.gif
  type: customlink-fulltext
eds_fulltext_links:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  url: http://library.stanford.edu/sfx?ID=doi:10.1016%2Fj.fcr.2016.04.011&genre=article&atitle=Yield%2C%20growth%20and%20grain%20nitrogen%20response%20to%20elevated%20CO2%20of%20five%20field%20pea%20%28Pisum%20sativum%20L.%29%20cultivars%20in%20a%20low%20rainfall%20environment&title=Field
    Crops Research&issn=03784290&isbn=&volume=196&issue=&date=20160901&aulast=Bourgault,
    Maryse&spage=1&pages=1-9&sid=EBSCO:ScienceDirect:S0378429016300958
  label: Check SFX for full text
  icon: http://library.stanford.edu/sfx/img/sfxmenu/SFXFinal.gif
  type: customlink-fulltext
eds_non_fulltext_links: []
id: edselp__S0378429016300958
eds_publication_id: 
eds_publication_is_searchable: 
eds_publication_scope_note: 
eds_fulltext_link: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  id: edselp__S0378429016300958
  links:
  - !ruby/hash:ActiveSupport::HashWithIndifferentAccess
    url: http://library.stanford.edu/sfx?ID=doi:10.1016%2Fj.fcr.2016.04.011&genre=article&atitle=Yield%2C%20growth%20and%20grain%20nitrogen%20response%20to%20elevated%20CO2%20of%20five%20field%20pea%20%28Pisum%20sativum%20L.%29%20cultivars%20in%20a%20low%20rainfall%20environment&title=Field
      Crops Research&issn=03784290&isbn=&volume=196&issue=&date=20160901&aulast=Bourgault,
      Maryse&spage=1&pages=1-9&sid=EBSCO:ScienceDirect:S0378429016300958
    label: Check SFX for full text
    icon: http://library.stanford.edu/sfx/img/sfxmenu/SFXFinal.gif
    type: customlink-fulltext
marcfield: 
```
